"""04

Revision ID: 0fc2b8a94531
Revises: ae27ceb548d9
Create Date: 2023-11-21 22:24:50.053961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fc2b8a94531'
down_revision: Union[str, None] = 'ae27ceb548d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('dice_count', sa.SmallInteger(), nullable=False),
    sa.Column('add_dice_count', sa.SmallInteger(), nullable=True),
    sa.Column('dice', sa.SmallInteger(), nullable=False),
    sa.Column('add_effect', sa.Text(), nullable=True),
    sa.Column('damage_type_alias', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['damage_type_alias'], ['damage_type.alias'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spell_effect')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell_effect',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('spell_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dice_count', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('dice', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('add_dice_count', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('damage_type_alias', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['damage_type_alias'], ['damage_type.alias'], name='spell_effect_ibfk_2'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], name='spell_effect_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('effect')
    # ### end Alembic commands ###
