"""05

Revision ID: 19b4709b76dd
Revises: 0fc2b8a94531
Create Date: 2023-11-29 09:28:08.125158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '19b4709b76dd'
down_revision: Union[str, None] = '0fc2b8a94531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('school_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('time_to_cast_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('distance_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('duration_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('components_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('spell_type_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('spell_mass_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('spell_roll_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('source_alias', sa.String(length=32), nullable=False))
    op.add_column('spell', sa.Column('entity_alias', sa.String(length=32), nullable=False))
    op.drop_constraint('spell_ibfk_1', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_7', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_10', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_5', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_9', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_2', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_4', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_6', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_3', 'spell', type_='foreignkey')
    op.drop_constraint('spell_ibfk_8', 'spell', type_='foreignkey')
    op.drop_column('components', 'id')
    op.add_column('components', sa.Column('alias', sa.String(length=32), primary_key=True, nullable=False))
    op.create_foreign_key(None, 'spell', 'duration', ['duration_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'source', ['source_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'entity', ['entity_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'components', ['components_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'distance', ['distance_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'spell_roll', ['spell_roll_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'time_to_cast', ['time_to_cast_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'school', ['school_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'spell_type', ['spell_type_alias'], ['alias'])
    op.create_foreign_key(None, 'spell', 'spell_mass', ['spell_mass_alias'], ['alias'])
    op.drop_column('spell', 'school')
    op.drop_column('spell', 'distance')
    op.drop_column('spell', 'entity')
    op.drop_column('spell', 'duration')
    op.drop_column('spell', 'spell_mass')
    op.drop_column('spell', 'time_to_cast')
    op.drop_column('spell', 'spell_type')
    op.drop_column('spell', 'spell_roll')
    op.drop_column('spell', 'components')
    op.drop_column('spell', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('source', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('components', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('spell', sa.Column('spell_roll', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('spell_type', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('time_to_cast', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('spell_mass', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('duration', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('entity', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('distance', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('spell', sa.Column('school', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.drop_constraint(None, 'spell', type_='foreignkey')
    op.create_foreign_key('spell_ibfk_8', 'spell', 'spell_roll', ['spell_roll'], ['alias'])
    op.create_foreign_key('spell_ibfk_3', 'spell', 'distance', ['distance'], ['alias'])
    op.create_foreign_key('spell_ibfk_6', 'spell', 'spell_type', ['spell_type'], ['alias'])
    op.create_foreign_key('spell_ibfk_4', 'spell', 'duration', ['duration'], ['alias'])
    op.create_foreign_key('spell_ibfk_2', 'spell', 'time_to_cast', ['time_to_cast'], ['alias'])
    op.create_foreign_key('spell_ibfk_9', 'spell', 'source', ['source'], ['alias'])
    op.create_foreign_key('spell_ibfk_5', 'spell', 'components', ['components'], ['id'])
    op.create_foreign_key('spell_ibfk_10', 'spell', 'entity', ['entity'], ['alias'])
    op.create_foreign_key('spell_ibfk_7', 'spell', 'spell_mass', ['spell_mass'], ['alias'])
    op.create_foreign_key('spell_ibfk_1', 'spell', 'school', ['school'], ['alias'])
    op.drop_column('spell', 'entity_alias')
    op.drop_column('spell', 'source_alias')
    op.drop_column('spell', 'spell_roll_alias')
    op.drop_column('spell', 'spell_mass_alias')
    op.drop_column('spell', 'spell_type_alias')
    op.drop_column('spell', 'components_alias')
    op.drop_column('spell', 'duration_alias')
    op.drop_column('spell', 'distance_alias')
    op.drop_column('spell', 'time_to_cast_alias')
    op.drop_column('spell', 'school_alias')
    op.add_column('components', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('components', 'alias')
    # ### end Alembic commands ###
