"""01

Revision ID: 6487840f47db
Revises: 
Create Date: 2023-11-05 20:22:01.338839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6487840f47db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distance', sa.Column('value', sa.Integer(), nullable=False))
    op.add_column('duration', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duration', 'value')
    op.drop_column('distance', 'value')
    # ### end Alembic commands ###
