"""03

Revision ID: ae27ceb548d9
Revises: ad51c05f6cb5
Create Date: 2023-11-19 22:04:53.377354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae27ceb548d9'
down_revision: Union[str, None] = 'ad51c05f6cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell_effect', 'half_damage_on_success')
    op.add_column('spell_roll', sa.Column('half_damage_on_success', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell_roll', 'half_damage_on_success')
    op.add_column('spell_effect', sa.Column('half_damage_on_success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
